name: deploy server
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: pnpm install
        working-directory: slides

      - name: Run build
        if: ${{ !(github.event.client_payload.file == '') }}
        run: pnpm run build ${{ github.event.client_payload.file }}
        working-directory: slides

      - name: Deploy
        id: deploy
        uses: kitabisa/cloudflare-pages-action@v2
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          branch: main
          production-branch: main
          package-manager: pnpm
          build-directory: ./dist
          project-name: test
          working-directory: ./slides

      - name: Telegram Notification
        if: ${{ !(github.event.client_payload.tgBotInfo.token == '') }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ github.event.client_payload.tgBotInfo.chatId }}
          token: ${{ github.event.client_payload.tgBotInfo.token }}
          message: |
            Deployed file `${{ github.event.client_payload.file }}` 
            Visit [here](${{ steps.deploy.outputs.pages-url }})
          format: markdown
